import type { Card, Enemy, EnemyIntent, Investigator } from '../types/game';

export const INITIAL_INVESTIGATOR: Investigator = {
  name: '愛德華·皮爾斯 (Edward Pierce)',
  occupation: '私家偵探',
  health: 25,
  maxHealth: 25,
  stamina: 3,
  maxStamina: 3,
  armor: 0,
  obols: 15,
};

export const INITIAL_DECK: Card[] = [
  {
    id: 'card_revolver_1',
    name: '左輪射擊',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'damage', value: 6 }],
    description: '造成 6 點物理傷害。',
    flavorText: '「點38子彈出膛的火光，是這座潮濕地窖中唯一的真實。」',
  },
  {
    id: 'card_revolver_2',
    name: '左輪射擊',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'damage', value: 6 }],
    description: '造成 6 點物理傷害。',
    flavorText: '「清脆的擊錘聲在腐臭的空氣中迴盪。」',
  },
  {
    id: 'card_punch_1',
    name: '重拳壓制',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'damage', value: 4 }],
    description: '造成 4 點物理傷害。',
    flavorText: '「在波士頓碼頭學會的街頭格鬥術，對怪物依然管用。」',
  },
  {
    id: 'card_punch_2',
    name: '重拳壓制',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'damage', value: 4 }],
    description: '造成 4 點物理傷害。',
    flavorText: '「皮肉撞擊的沉悶聲響令人作嘔。」',
  },
  {
    id: 'card_punch_3',
    name: '重拳壓制',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'damage', value: 4 }],
    description: '造成 4 點物理傷害。',
    flavorText: '「凡人的關節在哀鳴，但你別無選擇。」',
  },
  {
    id: 'card_bayonet_1',
    name: '軍刀突刺',
    category: 'combat',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    effects: [{ type: 'damage', value: 11 }],
    description: '消耗 2 點精力，造成 11 點重度物理傷害。',
    flavorText: '「帶著軍旅生涯的殘留記憶，你將鋒利的刺刀狠命扎入敵人的腐肉。」',
  },
  {
    id: 'card_cane_1',
    name: '鉛頭手杖',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'damage', value: 5 }],
    description: '造成 5 點物理傷害。',
    flavorText: '「紳士的防身行頭，手杖內部灌滿了實心黑鉛。」',
  },
  {
    id: 'card_cane_2',
    name: '鉛頭手杖',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'damage', value: 5 }],
    description: '造成 5 點物理傷害。',
    flavorText: '「精準打擊關節，讓畸形軀體為之頓挫。」',
  },
  {
    id: 'card_cover_1',
    name: '就地掩蔽',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'armor', value: 5 }],
    description: '獲得 5 點護甲值（跨回合持續累積）。',
    flavorText: '「翻倒厚重的橡木長桌，碎屑如驟雨般飛濺。」',
  },
  {
    id: 'card_breathe_1',
    name: '深呼吸',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    effects: [{ type: 'restore_sanity', value: 1 }],
    description: '將棄牌堆中 1 張卡牌洗回理智牌庫（回補 1 點理智）。',
    flavorText: '「緊閉雙眼，強迫狂亂跳動的心臟放緩節奏。」',
  },
];

export const GHOUL_INTENTS: EnemyIntent[] = [
  {
    type: 'attack',
    value: 6,
    name: '腐臭爪擊',
    description: '食屍鬼揮舞滴淌著黑血與腐土的利爪，預告造成 6 點傷害。',
  },
  {
    type: 'attack',
    value: 8,
    name: '撕咬猛撲',
    description: '食屍鬼如獵犬般伏地前衝，張開滿嘴銳齒預告造成 8 點傷害。',
  },
  {
    type: 'attack',
    value: 5,
    name: '尖銳咆哮',
    description: '刺耳的超聲波咆哮震撼耳膜，預告造成 5 點傷害。',
  },
];

export const INITIAL_GHOUL: Enemy = {
  id: 'enemy_ghoul_01',
  name: '食屍鬼 (Ghoul)',
  title: '墓穴的潛伏者',
  health: 30,
  maxHealth: 30,
  armor: 0,
  currentIntent: GHOUL_INTENTS[0],
  intentSequence: GHOUL_INTENTS,
  currentIntentIndex: 0,
};

