import type { Card } from '../../../types/game';

/**
 * 艾蓮諾·凡斯（秘術學者）專屬獎勵卡牌庫 (Tier 1 ~ Tier 4)
 */
export const OCCULTIST_REWARD_CARDS: Card[] = [
  // --- Tier 1 ---
  {
    id: 'reward_void_fire_1',
    name: '虛空烈焰',
    category: 'magic',
    costType: 'sanity',
    costValue: 2,
    isTemporary: false,
    tier: 1,
    occupations: ['occultist'],
    artworkUrl: '/cards/magic/card_magic_blast.webp',
    effects: [{ type: 'damage', value: 18 }],
    description: '造成 18 點秘術傷害。',
    flavorText: '「燃燒靈魂碎片釋放的星辰冷火。」',
  },
  {
    id: 'reward_dread_whisper_1',
    name: '恐懼低語',
    category: 'magic',
    costType: 'sanity',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['occultist'],
    artworkUrl: '/cards/magic/card_magic_gaze.webp',
    effects: [{ type: 'damage', value: 10 }],
    description: '造成 10 點秘術傷害。',
    flavorText: '「在敵人腦海中回放拉萊耶的潮汐聲。」',
  },
  {
    id: 'reward_astral_insight_1',
    name: '星界洞察',
    category: 'truth',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['occultist'],
    artworkUrl: '/cards/truth/card_silver_key.webp',
    effects: [
      { type: 'self_damage', value: 2 },
      { type: 'add_to_deck', value: 3 },
    ],
    description: '自身承受 2 點反噬傷害，向理智牌庫注入 3 張真相卡牌。',
    flavorText: '「意識升入無垠星穹，心智雖千瘡百孔，卻獲得浩瀚的安寧。」',
  },

  // --- Tier 2 ---
  {
    id: 'card_tier2_silver_blade',
    name: '破魔銀質短刃',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 2,
    occupations: ['occultist'],
    artworkUrl: '/cards/combat/card_ritual_dagger.webp',
    effects: [{ type: 'damage', value: 10 }],
    description: '造成 10 點物理傷害。',
    flavorText: '「刀刃浸過聖水與秘銀，對深潛者的黏滑厚皮有著致命的破甲奇效。」',
  },
  {
    id: 'card_tier2_frost_grasp',
    name: '深海冰霜之握',
    category: 'magic',
    costType: 'sanity',
    costValue: 2,
    isTemporary: false,
    tier: 2,
    occupations: ['occultist'],
    artworkUrl: '/cards/magic/card_magic_blast.webp',
    effects: [{ type: 'damage', value: 25 }],
    description: '造成 25 點秘術傷害。',
    flavorText: '「冰冷徹骨的洋流自異次元裂隙倒灌，連空氣中的水氣都凝結成尖銳冰刺。」',
  },
  {
    id: 'card_tier2_mind_shock',
    name: '心靈震波',
    category: 'magic',
    costType: 'sanity',
    costValue: 1,
    isTemporary: false,
    tier: 2,
    occupations: ['occultist'],
    artworkUrl: '/cards/magic/card_magic_gaze.webp',
    effects: [
      { type: 'damage', value: 14 },
      { type: 'draw', value: 1 },
    ],
    description: '造成 14 點秘術傷害，抽取 1 張卡牌。',
    flavorText: '「神經元在尖嘯中過載，將腦海中的混亂與回音直接烙印在敵人意識深處。」',
  },
  {
    id: 'card_tier2_forbidden_tablet',
    name: '禁忌海蝕石板殘卷',
    category: 'truth',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 2,
    occupations: ['occultist'],
    artworkUrl: '/cards/truth/card_silver_key.webp',
    effects: [
      { type: 'self_damage', value: 2 },
      { type: 'add_to_deck', value: 4 },
    ],
    description: '自身承受 2 點反噬傷害，向理智牌庫注入 4 張真相卡牌。',
    flavorText: '「石板上的非歐幾何符文正向外滲出幽綠磷光，閱讀它需要承受難以言喻的痛楚。」',
  },
  {
    id: 'card_tier2_silver_key_glow',
    name: '銀鑰指引微光',
    category: 'truth',
    costType: 'free',
    costValue: 0,
    isTemporary: false,
    tier: 2,
    occupations: ['occultist'],
    artworkUrl: '/cards/truth/card_silver_key.webp',
    effects: [
      { type: 'draw', value: 1 },
      { type: 'add_to_deck', value: 2 },
    ],
    description: '抽取 1 張卡牌，向理智牌庫注入 2 張真相卡牌。',
    flavorText: '「銀色鑰匙在虛空中劃過優雅弧線，照亮通往宇宙秩序的隱密回廊。」',
  },

  // --- Tier 3 ---
  {
    id: 'card_tier3_void_collapse',
    name: '虛空黑洞坍縮',
    category: 'magic',
    costType: 'sanity',
    costValue: 2,
    isTemporary: false,
    tier: 3,
    occupations: ['occultist'],
    artworkUrl: '/cards/magic/card_magic_blast.webp',
    effects: [{ type: 'damage', value: 34 }],
    description: '造成 34 點秘術傷害。',
    flavorText: '「空間維度在此處發生不可逆轉的扭曲，一切物質皆向著虛無的奇點崩陷。」',
  },
  {
    id: 'card_tier3_psionic_cleave',
    name: '深淵靈能撕裂',
    category: 'magic',
    costType: 'sanity',
    costValue: 1,
    isTemporary: false,
    tier: 3,
    occupations: ['occultist'],
    artworkUrl: '/cards/magic/card_magic_gaze.webp',
    effects: [{ type: 'damage', value: 20 }],
    description: '造成 20 點秘術傷害。',
    flavorText: '「靈能風暴猶如實質利刃，自神經深處劈開敵人的保護甲殼。」',
  },
  {
    id: 'card_tier3_rlyeh_codex',
    name: '拉萊耶原典啟示',
    category: 'truth',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 3,
    occupations: ['occultist'],
    artworkUrl: '/cards/truth/card_silver_key.webp',
    effects: [{ type: 'add_to_deck', value: 6 }],
    description: '向理智牌庫注入 6 張真相卡牌。',
    flavorText: '「沉睡千億年的深海真言在眼前展開，浩瀚的星辰秩序驅散了深淵狂亂。」',
  },
  {
    id: 'card_tier3_star_resonance',
    name: '超維星辰共鳴',
    category: 'truth',
    costType: 'free',
    costValue: 0,
    isTemporary: false,
    tier: 3,
    occupations: ['occultist'],
    artworkUrl: '/cards/truth/card_silver_key.webp',
    effects: [
      { type: 'armor', value: 10 },
      { type: 'add_to_deck', value: 3 },
    ],
    description: '獲得 10 點護甲，向理智牌庫注入 3 張真相卡牌。',
    flavorText: '「群星在遙遠天穹正位共振，為調查員的心智披上一層不可穿透的星光紗幕。」',
  },

  // --- Tier 4 Exclusive ---
  {
    id: 'card_tier4_void_annihilation',
    name: '超維虛空湮滅',
    category: 'magic',
    costType: 'sanity',
    costValue: 2,
    isTemporary: false,
    tier: 4,
    occupations: ['occultist'],
    artworkUrl: '/cards/magic/card_magic_blast.webp',
    effects: [{ type: 'damage', value: 42 }],
    description: '造成 42 點秘術傷害。',
    flavorText: '「宇宙黑洞深處的奇異點在眼前剎那綻放，將目光所及的一切狂暴異質徹底撕裂。」',
  },
  {
    id: 'card_tier4_astral_revelation',
    name: '源初星辰啟示',
    category: 'truth',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 4,
    occupations: ['occultist'],
    artworkUrl: '/cards/truth/card_silver_key.webp',
    effects: [
      { type: 'add_to_deck', value: 8 },
      { type: 'armor', value: 12 },
    ],
    description: '獲得 12 點護甲，向理智牌庫注入 8 張真相卡牌。',
    flavorText: '「當意識凌駕於群星之上，深淵的詛咒與瘋狂皆化為無垠宇宙中的一粒微塵。」',
  },
];
