import type { Card } from '../../../types/game';

/**
 * 中立通用卡牌庫 (全職業通用工具/道具牌，Tier 1 ~ Tier 4)
 */
export const NEUTRAL_CARDS: Card[] = [
  // --- Tier 1 ---
  {
    id: 'reward_ancient_amulet_1',
    name: '遠古護身符',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/skill/card_ancient_amulet.png',
    effects: [{ type: 'armor', value: 8 }],
    description: '獲得 8 點護甲。',
    flavorText: '「青銅上的深綠包漿散發著阻絕污穢的冰涼氣息。」',
  },
  {
    id: 'reward_first_aid_1',
    name: '應急急救包',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/skill/card_first_aid.png',
    effects: [
      { type: 'armor', value: 3 },
      { type: 'restore_sanity', value: 2 },
    ],
    description: '獲得 3 點護甲，洗回 2 張卡牌至理智牌庫。',
    flavorText: '「酒精與繃帶能穩固搖搖欲墜的精神防線。」',
  },
  {
    id: 'reward_field_bandage',
    name: '戰地急救繃帶',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    keywords: ['exhaust'],
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/skill/card_field_bandage.png',
    effects: [
      { type: 'heal', value: 4 },
      { type: 'armor', value: 4 },
    ],
    description: '【消耗】立即恢復 4 點肉體生命值，並獲得 4 點護甲。打出後移出戰鬥。',
    flavorText: '「浸滿卡波酸消毒液的無菌繃帶，是長途探索中挽救性命的最後底牌。」',
  },
  {
    id: 'reward_tactical_feint',
    name: '戰術佯攻',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/combat/card_tactical_feint.png',
    effects: [
      { type: 'apply_status', statusType: 'vulnerable', value: 2, target: 'enemy' },
    ],
    description: '使目標陷入 2 層【易傷】破綻狀態。',
    flavorText: '「虛晃一招誘敵深入，撕開怪物厚重防禦下的致命死角。」',
  },
  {
    id: 'reward_calm_observation',
    name: '冷靜觀察',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/skill/card_calm_observation.png',
    effects: [
      { type: 'armor', value: 5 },
      { type: 'draw', value: 2 },
    ],
    description: '獲得 5 點護甲，並敏銳抽取 2 張卡牌。',
    flavorText: '「在震耳欲聾的嘶吼聲中強自鎮定，洞悉敵怪攻擊軌跡中的破綻。」',
  },

  // --- Tier 2 ---
  {
    id: 'reward_remnant_seal',
    name: '舊印殘印',
    category: 'truth',
    costType: 'free',
    costValue: 0,
    isTemporary: false,
    tier: 2,
    keywords: ['exhaust'],
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/truth/card_remnant_seal.png',
    effects: [
      { type: 'armor', value: 12 },
      { type: 'restore_sanity', value: 2 },
    ],
    description: '【消耗】獲得 12 點護甲，洗回 2 張卡牌至理智牌庫。打出後移出戰鬥。',
    flavorText: '「殘缺的古印石片在掌心化為微光碎屑，為凡人擋下太古污染的致命侵蝕。」',
  },
  {
    id: 'card_tier2_rapid_suture',
    name: '戰地快速縫合',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 2,
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/skill/card_rapid_suture.png',
    effects: [
      { type: 'armor', value: 6 },
      { type: 'restore_sanity', value: 3 },
    ],
    description: '獲得 6 點護甲，洗回 3 張卡牌至理智牌庫。',
    flavorText: '「即便手指被寒風凍得發僵，依然熟練地穿針引線，穩住潰散的精神防線。」',
  },

  // --- Tier 3 ---
  {
    id: 'card_tier3_sanity_anchor',
    name: '極限精神錨定',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 3,
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/skill/card_sanity_anchor.png',
    effects: [
      { type: 'armor', value: 8 },
      { type: 'restore_sanity', value: 5 },
    ],
    description: '獲得 8 點護甲，洗回 5 張卡牌至理智牌庫。',
    flavorText: '「以古代舊印銘文將狂暴渙散的心靈死死固定在理性之錨上。」',
  },

  // --- Tier 4 Exclusive ---
  {
    id: 'card_tier4_elder_aegis',
    name: '舊神庇護之陣',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 4,
    occupations: ['investigator', 'occultist'],
    artworkUrl: '/cards/skill/card_elder_aegis.png',
    effects: [
      { type: 'armor', value: 24 },
      { type: 'draw', value: 2 },
    ],
    description: '獲得 24 點護甲，抽取 2 張卡牌。',
    flavorText: '「五芒星光在周身環繞，不可名狀的混沌污穢在光芒前如同初雪般消融。」',
  },
];
