import type { Card } from '../../../types/game';

/**
 * 愛德華·皮爾斯（私家偵探）專屬獎勵卡牌庫 (Tier 1 ~ Tier 4)
 */
export const INVESTIGATOR_REWARD_CARDS: Card[] = [
  // --- Tier 1 ---
  {
    id: 'reward_shotgun_1',
    name: '雙管獵槍',
    category: 'combat',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [
      { type: 'damage', value: 16 },
      { type: 'lose_armor', value: 5 },
    ],
    description: '造成 16 點物理傷害；【強烈後座力】打出後自身失去 5 點護甲。',
    flavorText: '「近距離的轟鳴撕裂了陰暗中的任何可怖實體。」',
  },
  {
    id: 'reward_quick_draw_1',
    name: '快速拔槍',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [
      { type: 'damage', value: 6 },
      { type: 'draw', value: 1, condition: { type: 'first_card_played' } },
      { type: 'gain_stamina', value: 1, condition: { type: 'first_card_played' } },
    ],
    description: '造成 6 點物理傷害；若為本回合打出的首張卡牌，回復 1 點精力並抽取 1 張卡牌。',
    flavorText: '「肌肉記憶超越了大腦對恐懼的本能遲疑。」',
  },
  {
    id: 'reward_tactical_roll_1',
    name: '戰術翻滾',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/skill/card_cover.webp',
    effects: [
      { type: 'armor', value: 4 },
      { type: 'draw', value: 1 },
    ],
    description: '獲得 4 點護甲，抽取 1 張卡牌。',
    flavorText: '「在碎石堆中翻滾尋找下一個反擊角度。」',
  },
  {
    id: 'reward_double_tap',
    name: '雙發速射',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_double_tap.png',
    effects: [{ type: 'damage', value: 4, hitCount: 2 }],
    description: '造成 4 點物理傷害 × 2 段（每段獨立享受【力量】與【易傷】印記加成）。',
    flavorText: '「在怪物撲上前，兩顆子彈已帶著火光精準破膛而出。」',
  },
  {
    id: 'reward_veteran_instinct',
    name: '老兵本能',
    category: 'skill',
    costType: 'free',
    costValue: 0,
    isTemporary: false,
    tier: 1,
    keywords: ['innate', 'exhaust'],
    occupations: ['investigator'],
    artworkUrl: '/cards/skill/card_veteran_instinct.png',
    effects: [
      { type: 'armor', value: 6 },
      { type: 'apply_status', statusType: 'might', value: 2, target: 'self' },
    ],
    description: '【固有】【消耗】獲得 6 點護甲與 2 層【力量】印記。開局必定抽至手中，打出後移出戰鬥。',
    flavorText: '「在壕溝戰中淬煉出的死亡嗅覺，讓你比怪物更快進入備戰狀態。」',
  },

  // --- Tier 2 ---
  {
    id: 'reward_shield_slam',
    name: '護甲猛擊',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 2,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_shield_slam.png',
    effects: [{ type: 'damage', value: 4, scaleFrom: 'armor', scaleMultiplier: 1.0 }],
    description: '造成 4 點物理傷害，並附加等同於當前護甲 100% 的額外物理傷害。',
    flavorText: '「將沉重鐵盾或堅硬掩體狠命向前撞擊，將積蓄的防守之勢化為暴烈反擊。」',
  },
  {
    id: 'reward_weakpoint_snipe',
    name: '弱點狙擊',
    category: 'combat',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    tier: 2,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_weakpoint_snipe.png',
    effects: [
      {
        type: 'damage',
        value: 12,
        condition: { type: 'target_has_status', statusType: 'vulnerable', multiplier: 2 },
      },
    ],
    description: '造成 12 點物理傷害；若目標處於【易傷】狀態，傷害翻倍為 24 點！',
    flavorText: '「屏住呼吸，透過準星直擊不可名狀軀體中最脆弱的肉瘤裂縫。」',
  },
  {
    id: 'card_tier2_pump_shotgun',
    name: '泵動式散彈槍',
    category: 'combat',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    tier: 2,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [
      { type: 'damage', value: 12 },
      { type: 'break_armor', value: 0 },
    ],
    description: '造成 12 點物理傷害，並【擊碎目標所有當前護甲】。',
    flavorText: '「潮濕海風無法阻止機械撞針的咆哮，轟鳴聲在海蝕洞穴深處激起陣陣回音。」',
  },
  {
    id: 'card_tier2_iron_will',
    name: '鋼鐵意志屏障',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 2,
    occupations: ['investigator'],
    artworkUrl: '/cards/skill/card_cover.webp',
    effects: [{ type: 'armor', value: 12 }],
    description: '獲得 12 點護甲。',
    flavorText: '「在深海異形的非人注視下，緊握雙拳，以鋼鐵般的理智封鎖恐懼。」',
  },

  // --- Tier 3 ---
  {
    id: 'card_tier3_dum_dum',
    name: '達姆高爆彈連射',
    category: 'combat',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    tier: 3,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [
      { type: 'damage', value: 6, hitCount: 4 },
      { type: 'apply_status', target: 'enemy', statusType: 'vulnerable', value: 2 },
    ],
    description: '造成 6 點物理傷害 × 4 段（共計 24 點物理傷害），並使目標陷入 2 層【易傷】狀態。',
    flavorText: '「開花彈在接觸肉體的瞬間引爆，即便是舊日支配者的僕從亦難以承受此等破壞力。」',
  },
  {
    id: 'card_tier3_demolition_pack',
    name: '軍用特種炸藥包',
    category: 'combat',
    costType: 'stamina',
    costValue: 3,
    isTemporary: false,
    tier: 3,
    keywords: ['exhaust'],
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [
      { type: 'damage', value: 40 },
      { type: 'apply_status', target: 'enemy', statusType: 'bleed', value: 3 },
      { type: 'apply_status', target: 'enemy', statusType: 'vulnerable', value: 2 },
    ],
    description: '造成 40 點物理傷害，並對目標施加 3 層【流血】與 2 層【易傷】。【消耗】打出後移出戰鬥。',
    flavorText: '「工兵守則第一條：只要裝藥足夠，世上沒有炸不開的門——也沒有炸不死的怪物。」',
  },
  {
    id: 'card_tier3_impenetrable_bastion',
    name: '不可侵犯之壁',
    category: 'skill',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    tier: 3,
    occupations: ['investigator'],
    artworkUrl: '/cards/skill/card_cover.webp',
    effects: [{ type: 'armor', value: 22 }],
    description: '獲得 22 點護甲。',
    flavorText: '「無懼非人泰克利利哀鳴，調查員築起凡人血肉所能構築的最堅固壁壘。」',
  },

  // --- Tier 4 Exclusive ---
  {
    id: 'card_tier4_god_slayer',
    name: '屠神裁決爆轟',
    category: 'combat',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    tier: 4,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [{ type: 'damage', value: 5, hitCount: 6, piercing: true }],
    description: '造成 5 點物理傷害 × 6 段（真實穿刺，無視護甲直扣生命值）。',
    flavorText: '「凡人的工藝與禁忌秘銀在此刻昇華，這一擊的威力足以讓舊日支配者的血脈為之顫慄。」',
  },
];
