import type { Card } from '../../../types/game';

/**
 * 愛德華·皮爾斯（私家偵探）起始牌組卡牌 (12 張)
 */
export const INVESTIGATOR_STARTER_CARDS: Card[] = [
  {
    id: 'card_revolver_1',
    name: '左輪射擊',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [{ type: 'damage', value: 6 }],
    description: '造成 6 點物理傷害。',
    flavorText: '「點38子彈出膛的火光，是這座潮濕地窖中唯一的真實。」',
  },
  {
    id: 'card_revolver_2',
    name: '左輪射擊',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_revolver.webp',
    effects: [{ type: 'damage', value: 6 }],
    description: '造成 6 點物理傷害。',
    flavorText: '「清脆的擊錘聲在腐臭的空氣中迴盪。」',
  },
  {
    id: 'card_punch_1',
    name: '重拳壓制',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_punch.webp',
    effects: [
      { type: 'damage', value: 4 },
      { type: 'armor', value: 2 },
    ],
    description: '造成 4 點物理傷害，獲得 2 點護甲。',
    flavorText: '「在波士頓碼頭學會的街頭格鬥術，對怪物依然管用。」',
  },
  {
    id: 'card_punch_2',
    name: '重拳壓制',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_punch.webp',
    effects: [
      { type: 'damage', value: 4 },
      { type: 'armor', value: 2 },
    ],
    description: '造成 4 點物理傷害，獲得 2 點護甲。',
    flavorText: '「皮肉撞擊的沉悶聲響令人作嘔。」',
  },
  {
    id: 'card_punch_3',
    name: '重拳壓制',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_punch.webp',
    effects: [
      { type: 'damage', value: 4 },
      { type: 'armor', value: 2 },
    ],
    description: '造成 4 點物理傷害，獲得 2 點護甲。',
    flavorText: '「凡人的關節在哀鳴，但你別無選擇。」',
  },
  {
    id: 'card_bayonet_1',
    name: '軍刀突刺',
    category: 'combat',
    costType: 'stamina',
    costValue: 2,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_bayonet.webp',
    effects: [{ type: 'damage', value: 11 }],
    description: '造成 11 點物理傷害。',
    flavorText: '「帶著軍旅生涯的殘留記憶，你將鋒利的刺刀狠命扎入敵人的腐肉。」',
  },
  {
    id: 'card_cane_1',
    name: '鉛頭手杖',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_cane.webp',
    effects: [{ type: 'damage', value: 5 }],
    description: '造成 5 點物理傷害。',
    flavorText: '「紳士的防身行頭，手杖內部灌滿了實心黑鉛。」',
  },
  {
    id: 'card_cane_2',
    name: '鉛頭手杖',
    category: 'combat',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/combat/card_cane.webp',
    effects: [{ type: 'damage', value: 5 }],
    description: '造成 5 點物理傷害。',
    flavorText: '「精準打擊關節，讓畸形軀體為之頓挫。」',
  },
  {
    id: 'card_cover_1',
    name: '就地掩蔽',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    keywords: ['retain'],
    occupations: ['investigator'],
    artworkUrl: '/cards/skill/card_cover.webp',
    effects: [{ type: 'armor', value: 5 }],
    description: '【保留】獲得 5 點護甲。',
    flavorText: '「翻倒厚重的橡木長桌，碎屑如驟雨般飛濺。」',
  },
  {
    id: 'card_breathe_1',
    name: '深呼吸',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/skill/card_breathe.webp',
    effects: [{ type: 'restore_sanity', value: 1 }],
    description: '洗回 1 張卡牌。',
    flavorText: '「緊閉雙眼，強迫狂亂跳動的心臟放緩節奏。」',
  },
  {
    id: 'card_sedative_1',
    name: '醫療鎮定劑',
    category: 'skill',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/skill/card_sedative.webp',
    effects: [{ type: 'restore_sanity', value: 2 }],
    description: '洗回 2 張卡牌。',
    flavorText: '「刺鼻的化學藥劑推入靜脈，混亂的囈語暫時歸於死寂。」',
  },
  {
    id: 'card_truth_fragment_1',
    name: '舊日殘頁',
    category: 'truth',
    costType: 'stamina',
    costValue: 1,
    isTemporary: false,
    tier: 1,
    occupations: ['investigator'],
    artworkUrl: '/cards/truth/card_truth_fragment.webp',
    effects: [
      { type: 'self_damage', value: 2 },
      { type: 'add_to_deck', value: 2 },
    ],
    description: '自身承受 2 點反噬傷害，向理智牌庫注入 2 張真相卡牌。',
    flavorText: '「窺見了世界真實的一角，肉身在戰慄，但混亂的心智為之驟然清醒。」',
  },
];
